# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- refs/tags/*
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
  displayName: 'Install Node.js'

- script: |
    npm config set spin false
    npm install -g phantomjs-prebuilt
    phantomjs --version
    yarn install
  displayName: 'Prepare'

- script:
    npm test
  displayName: 'Test'

- script: |
    npm run build
    npm pack
  displayName: 'Build'

- task: GithubRelease@0 
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: joseph-cliqz
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    tag: '$(Build.SourceBranchName)'
    assets: '$(Build.ArtifactStagingDirectory)/*.tgz'
    isPreRelease: true